name: dart_mvc
description: >
  A minimal and classic mvc implementation of dart.
version: 0.0.1
author: Jaron Tai <jaroncn@gmail.com>
#homepage: https://www.example.com
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: any
